This is makeindex, version 2.15 [TeX Live 2016] (kpathsea + Thai support).
Scanning style file ./main.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file main.acn....done (63 entries accepted, 0 rejected).
Sorting entries....done (389 comparisons).
Generating output file main.acr....done (61 lines written, 0 warnings).
Output written in main.acr.
Transcript written in main.alg.
